### ISSUE TITLE
Not finding all h2 tags.

### ISSUE THREAD

**Issue by fcherman** [h5o/h5o-chrome#20]
The dropdown does not catch all headings at a given level.  
![penndot home page - did not leverage hierarchical headings](https://cloud.githubusercontent.com/assets/59314/19630107/95730b6e-9938-11e6-8a34-19429d840e90.png)

For example, it did not catch the h2 heading shown below on the page and in the Chrome inspector.
![image](https://cloud.githubusercontent.com/assets/59314/19630116/c950893e-9938-11e6-83fc-6dac2afbbabf.png)

**Comment by dominykas** [comment]
Can you post an exact URL to this page, please?

**Comment by sughero3** [comment]
I do not understand ??

**Comment by fcherman** [comment]
This is the URL.

http://www.penndot.gov/Pages/default.aspx

**Comment by dominykas** [comment]
This is because the page is using tables for layout - [according to the spec](https://www.w3.org/TR/html5/sections.html#headings-and-sections) `td` is a "sectioning root", i.e. it has its own outline and is not part of the page outline.

I'll close this issue, but I'd happily accept a PR to display multiple sectioning roots.

**Comment by fcherman** [comment]
I'd be happy to give you a pr if I knew what it was. ;-)

**Comment by sughero3** [comment]
Now I begin to understand, but because I come notifications in my email account? ... [???]
